### ISSUE TITLE
Same commit message twice for each deploy

### ISSUE THREAD

**Issue by pdewouters** [stephenharris/grunt-wp-deploy#10]
![screenshot 2014-09-02 10 04 27](https://cloud.githubusercontent.com/assets/30460/4118489/d2f642bc-32a1-11e4-860a-3d1404ef8efe.png)

**Comment by stephenharris** [comment]
This if fixed in 1.1.0 (sorry for the delay, the update had be sitting, forgotten, on my hard drive)
