### ISSUE TITLE
[Feature Request] Prompt for 'password'

### ISSUE THREAD

**Issue by cfoellmann** [stephenharris/grunt-wp-deploy#15]
I would love to use this but it just doesn't work on Windows. My alternative is to run it on the vagrant box (VVV) via ssh. Should be easy, right? _NO_

A prompt for the password after username would be sooo great.

**Comment by stephenharris** [comment]
I've given up on `git svn`. In any case, my typical set up is using `git` repo is for development, and `svn` just for deployment. 

I'm about to add the `--force-interactive` option, and I'm currently working on #2 at the moment.

**Comment by atimmer** [comment]
Any progress on this? Can I help in some way?

**Comment by nekojira** [comment]
+1

**Comment by stephenharris** [comment]
Sorry, being meaning to do this for a while. This is (should be) fixed on the develop branch of this repo. If anyone is able to check that out and test it, and verify it works, then I'd be happy to release it.

You would just need to check out the repo and replace the contents of your node_modules/grunt-wp-deploy directory the contents of the repo.

**Comment by nekojira** [comment]
thanks @stephenharris this works great for me

**Comment by nekojira** [comment]
note: if someone doesn't get it working following https://github.com/stephenharris/grunt-wp-deploy/issues/15#ref-commit-4f981ea as @stephenharris  suggested, it's likely you need to update svn to 1.8

**Comment by stephenharris** [comment]
Thanks @nekojira  I'll aim to get this properly released on npm this weekend.

**Comment by nekojira** [comment]
http://giphy.com/gifs/reactiongifs-5dDjN9OaDzJ0Q
