### ISSUE TITLE
Cannot update assets without deploying code

### ISSUE THREAD

**Issue by markjaquith** [stephenharris/grunt-wp-deploy#16]
What if I want to update my banner, but I don't have a new version to release?

**Comment by stephenharris** [comment]
Not possible at present :(. To be honest, updating assets was an after thought, and wanting to update them independently of the codebase just wasn't on my radar. 

Equally it would be nice to update trunk without necessitating a tagged release (e.g. updating 'tested up to'). This would all require a re-think of how the plug-in is structured as the original goal was simply to automate tagging a new release.

Unfortunately I wont' be able to work on this much for the next 6-9 months at least. But happy to accept PRs in that direction.

**Comment by shivapoudel** [comment]
@markjaquith @stephenharris I think if the git tag doesn't exist then we can simply disable the automated svn tag update and commit the assets for screenshot and banners with their latest commit applied :)

**Comment by jancbeck** [comment]
I just wanted to bump my "Tested up to" string to 4.3 and as the email I got from wp.org suggest:
> For each plugin that is compatible, you don't need to release a new version -- just change the stable version's readme value.

I could not deploy the changed plugin without adding tagging a new deploy version. 
Is this the same issue then?

**Comment by stephenharris** [comment]
@jancbeck  -not quite:

This script doesnt allow checking in changes to an existing tag which is required if you want to update the 'tested up to' (it requires an update to both trunk and the stable tag).

**Comment by mundschenk-at** [comment]
I'd also appreciate being able to separatly update `assets/` as well as `trunk/` and an existing version tag. I recently bumped into this problem and used the `-f` switch, resulting in the whole `trunk/` being added as a subdirectory to the existing tagged version.

**Comment by mundschenk-at** [comment]
I've added a PR for allowing separate deployment of /trunk and /assets without the need for tagging a release (#25).

**Comment by stephenharris** [comment]
https://github.com/stephenharris/grunt-wp-deploy/commit/19b4b58a043674e6c12a0cd1cd4b0b227e84356b adds options `deploy_trunk` and `deploy_tag` (both default to `true`). You can use those settings to either to trunk only or trunk and tag (you can't deploy to a tag but not trunk).

Separately you can set the `assets_dir` to `false` to prevent commits to the assets directory. 

As wp_deploy is a multi-task you can configure multiple tasks to be able to deploy to trunk / trunk+tag / assets / everything
