### ISSUE TITLE
Failed to commit to trunk: Error: Command failed: svn: E215004: Authentication failed and interactive prompting is disabled;

### ISSUE THREAD

**Issue by nekojira** [stephenharris/grunt-wp-deploy#18]
This is a great grunt plugin! Thanks!

I have the same error as #7.

grunt-wp-deploy runs fine but it stops when it's about to commit the trunk and the tag to wordpress svn

    Warning: Failed to commit to trunk: Error: Command failed: svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
    svn: E215004: Commit failed (details follow):
    svn: E215004: No more credentials or we tried too many times.
    Authentication failed

This might as well be a SVN configuration issue but I did not have this issue while running svn from terminal manually.

I have entered my wordpress.org username matching the svn repo when prompted or tried setting it in Gruntfile config.

I have edited my `~/.subversion/config` file to set `password-stores =` to blank as well as `  interactive-conflicts = yes` and also cleared my keyring files (I'm on ubuntu 15.04).

I still can't get it to work. I think others might incur in the same issue, perhaps it's worth to publish a workaround for this in the grunt plugin readme or wiki?

**Comment by nekojira** [comment]
resolved by #15

**Comment by robert-john-concepcion** [comment]
whats your solution man? thanks
