### ISSUE TITLE
Expected 'readme.txt' in plugin, if case is different (e.g. README.txt) wp deploy will halt

### ISSUE THREAD

**Issue by unfulvio** [stephenharris/grunt-wp-deploy#19]
I ran in this issue on a plugin that had its readme.txt file in capital letters. `grunt-wp-deploy` will complain that `readme.txt` cannot be found.

To reproduce the issue just rename a readme.txt in README.txt

I don't think it's a big issue but I just wanted report it here. If I have a fix will submit a PR.

**Comment by stephenharris** [comment]
Thanks @nekojira  - does wordpress.org not care about the casing? (I've never tried).

If not, then I'm happy to fix this. If it does, then this is useful sanity check.

**Comment by nekojira** [comment]
apparently not... plugins that had this were already on SVN with uppercase so I guess it's not an issue 

(at least is not as bad as git case sensitive madness - while renaming README to readme while in git it can lead to very annoying conflicts)

**Comment by stephenharris** [comment]
So this is harder to fix than I expected. Grunt.file doesn't expose an option for case insensitive filenames. So the solutions left to us, is to loop through all (reasonable) casings of 'readme' or expose it as an option. 

Neither of which is particularly appealing...

**Comment by nekojira** [comment]
how about asking users to type the filename of their readme file?

`"Please type the name of your readme file (case sensitive)."`

some possible answers: README.txt, readme.txt, Readme.txt, ReadMe.txt... (haven't checked if camelcase is supported by wordpress.org svn though) - I know sounds weird, but people do unexpected things...

**Comment by stephenharris** [comment]
That would interrupt the automation (Granted, this already happens with 'Are you sure?')

Perhaps exposing an option is suitable here. It would allow for any casing.

**Comment by nekojira** [comment]
the task requires a bit of attention, so asking for confirmation is absolutely fine - it's also likely this task will be always at the end of a task array (build, test, deploy...) so it won't really interrupt it

I think so too, exposing option would be most portable, you only write it once.

**Comment by swissspidy** [comment]
Just FYI: The plugin directory absolutely supports `readme.md` files nowadays. In our plugin, we don't have a `readme.txt` file anymore, that's why I stumbled upon the `Warning: readme.txt file not not found` error.

I think the plugin should check for `README.txt, readme.txt, README.md, readme.md`. I wouldn't check for any other combinations (CamelCase etc.) as those should be veery uncommon.

**Comment by nekojira** [comment]
my 2c - personally I like seeing a readme.txt and readme.md separation

WordPress reads information from readme.txt headers which is by today's standards a poor choice 

current readme.txt from WordPress is all but a useful readme when opened in a text editor, or even here on GitHub; it crams information to be parsed by the WordPress install, the WordPress plugin directory, changelogs, screenshots metadata and much more... When parsed on the directory is more readable but if this readme was conceived today, we would probably have a plugin.json instead and an actual readme.md like on GitHub.

So, I tend to have both in WordPress plugin projects, one to be parsed on the directory/install and a readme.md with nicely styled info. I also tend to have a separate changelog.md with just changelog info. It's not just me, I've seen others adopting the same approach.

Therefore I think this plugin should not look for a readme.md as users may have both. Camelcase (ReadMe.txt) or especially uppercase (README.txt) are far from uncommon in my opinion.

**Comment by swissspidy** [comment]
> Therefore I think this plugin should not look for a readme.md as users may have both.

I understand your use case. I sometimes also have two readme files. However, my suggestion was to only look for `readme.md` only when a `readme.txt` isn't available. This doesn't break anything.

If you have two readme files, nothing changes. If you only have a `readme.md`, the script assumes this must be your readme for the repository (especially when it has a valid readme header!).

> Camelcase (ReadMe.txt) or especially uppercase (README.txt) are far from uncommon in my opinion.

I didn't say `README.txt` is uncommon. I'm sure the script can also check for filenames written in CamelCase, my point was more to not check _every_ `rEaDmE.txt` filename combination.

**Comment by stephenharris** [comment]
@swissspidy I didn't realise that .org accepted `readme.md`. That would be great for me - it would render https://github.com/stephenharris/wp-readme-to-markdown obsolete which had been bugging me really `.md` is the source and (I had assumed) `.txt` version was the necessary 'production' version. Which plug-in are you just using `.md`?

I think your suggestion might be best: to check (in this order) the existence of:

 1. readme.txt
 2. readme.md
 3. README.txt
 4. README.md
 5. ReadMe.txt
 6. ReadMe.md

and using whichever it finds first.

That way the change is backwards compatible and covers most reasonable cases. @nekojira This won't prevent you using two different readme files.

**Comment by swissspidy** [comment]
I'm using it in the [WP Team List](https://wordpress.org/plugins/wp-team-list/) plugin ([GitHub](https://github.com/wearerequired/rplus-wp-team-list)) and in [every plugin here](https://profiles.wordpress.org/pluginkollektiv) without any problems.

Source: https://twitter.com/Otto42/status/623272923663437824

On the other hand, after using your readme-to-markdown converter, I've also been using some simple search-replace script (about 4 regular expressions) to do it the other way around.

**Comment by nekojira** [comment]
hey fine by me in that case :+1: 

I used too wp to markdown, but simply put I don't like how contents of readme.txt need to be organized to match WordPress.org requirements, prefer to enter different content across the two files although not very 'dry' solution

ps OT: @stephenharris I think you need to update the release tag so npm can catch up with the last updates in the repo

**Comment by swissspidy** [comment]
Any way we can help with this? Not sure I got the time to work on a PR :/

**Comment by stephenharris** [comment]
Just working on one now :)

**Comment by stephenharris** [comment]
Priority of ReadMes is now:

- readme.txt
- README.txt
- ReadMe.txt
- readme.md
- README.md
- ReadMe.md

due to case insensitivity on some operating systems.
