### ISSUE TITLE
Can we have one more option to specify an alternative {plugin-slug}.php file?

### ISSUE THREAD

**Issue by nekojira** [stephenharris/grunt-wp-deploy#20]
Enhancement suggestion.

Although recommended, the main file of the plugin containing php headers used by the WordPress plugins api and the wordpress.org plugins directory, does not need to match the plugin slug (the directory in plugins.svn.wordpress.org). WordPress intelligently looks for the php file in plugin root with the right headers.

However, currently these two need to match in grunt-wp-deploy as mentioned in https://github.com/stephenharris/grunt-wp-deploy#before-you-start-youll-need. Could we have an option to indicate a specific php file to look for?

thank you

**Comment by stephenharris** [comment]
I'm happy for this to be included but I'm a bit time poor at the moment - so if you/anybody wants to make a pull request then I'll push out an update.

**Comment by nekojira** [comment]
eh likewise :) I understand, in fact thank you for making this grunt plugin, it's handy 
I will try to look at thi this weekend and maybe issue PR - if not this week the next one

**Comment by nekojira** [comment]
hey not sure if you got the notification from the PR, but I think it should work now
