### ISSUE TITLE
Fatal error: Checkout of "some repo" unsuccessful: Error: stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by ntwb** [stephenharris/grunt-wp-deploy#33]
Just updated and now using grunt-wp-deploy v1.2.1 I received the following error:

```shell
$ grunt wp_deploy
Running "wp_deploy:trunk" (wp_deploy) task
[?] What's your SVN username? some-fake-username
Checking out http://plugins.svn.wordpress.org/buddypress...
Fatal error: Checkout of "http://plugins.svn.wordpress.org/buddypress"unsuccessful: Error: stdout maxBuffer exceeded
```

My config:
```js
		wp_deploy:{
			trunk: {
				options: {
					build_dir: 'build',
					deploy_tag: false,
					deploy_trunk: true,
					plugin_slug: 'buddypress',
					tmp_dir: 'tmp-wp-deploy'
				}
			}
		}
```

The content of the `tmp-wp-deploy` folder includes:
• All of the `tmp-wp-deploy/buddypress/assets` folder ✅ 
• All of the `tmp-wp-deploy/buddypress/branches` folder ✅ 
• Only 5 of the ~120 tags `tmp-wp-deploy/buddypress/branches` folder ❌ 
• Trunk is not checked out at all `tmp-wp-deploy/buddypress/trunk` folder ❌ 
• Source https://plugins.trac.wordpress.org/browser/buddypress

I think this is partially a BuddyPress issue that it shouldn't have ~120 tags at `plugins.svn`, but also `grunt-wp-deploy` was only able to check out 5 tags, if BuddyPress removes many of the old tags from the plugins repo it will still have more than 5 tags, maybe somewhere around 10-20.

Thoughts @stephenharris ?

**Comment by stephenharris** [comment]
You can set the limit of `maxBuffer` via  the `max_buffer` setting. It defaults to `200*1024`

**Comment by stephenharris** [comment]
This quite common really in large plug-ins, or even smaller plugins with a lot of tags.

**Comment by stephenharris** [comment]
This will hopefully be fixed with https://github.com/stephenharris/grunt-wp-deploy/commit/f6170cdd7e50a2e07c51b823aa2d4014de2fe4e3
