### ISSUE TITLE
RegExp for stable tag doesn't match lists in markdown

### ISSUE THREAD

**Issue by ocean90** [stephenharris/grunt-wp-deploy#34]
Example header of a README.md:

```markdown
# Plugin Name #
* Contributors: contributor
* Requires at least: 4.2
* Tested up to: 4.7
* Stable tag: 2.0.1
* License: GPLv2 or later
* License URI: http://www.gnu.org/licenses/gpl-2.0.html
```

The [current RegExp](https://github.com/stephenharris/grunt-wp-deploy/blob/ec0330d985e4f3964057dd0cab8619e3d23bb589/tasks/wp_deploy.js#L102) requires that the line starts with `Stable Tag`. In my example it starts with an asterisk because of the list.

Allowing spaces, tabs and the asterisk would fix parsing the readme:
```diff
- var readmeVersion = readme.match( new RegExp("^Stable tag:\\s*(\\S+)","im") );
+ var readmeVersion = readme.match( new RegExp("^[ \t*]*Stable tag:\\s*(\\S+)","im") );
```

Thoughts?

**Comment by stephenharris** [comment]
Yes, I see no reason why that shouldn't be supported.
