### ISSUE TITLE
Add support for .distignore

### ISSUE THREAD

**Issue by westonruter** [stephenharris/grunt-wp-deploy#36]
WP-CLI supports a `.distignore` file which is intended to be used in the release process. See https://github.com/wp-cli/scaffold-command/blob/master/templates/plugin-distignore.mustache

It would be be handy if `grunt-wp-deploy` could read from these files when building the file list, if for example a `build` directory was not supplied in the Gruntfile.

**Comment by johnbillion** [comment]
There's also a `.gitattributes` file that's commonly used to ignore files from a package.

**Comment by johnbillion** [comment]
I don't think file ignorance should be the responsibility of this package. The build process should take care of copying the desired files into the build directory.

I'm using the `gitattributes-globs` package from NPM to automatically ignore files in my `.gitignore` file, I'm pretty sure it works for the `.distignore` syntax too.

https://github.com/johnbillion/user-switching/blob/e64483b929f0add59c4c9e8f333ac27753db140c/Gruntfile.js#L10-L12

**Comment by stephenharris** [comment]
Sorry, I missed this ticket when originally posted. I'm inclined to agree with John here, this package was only intended to be a wrapper for SVN to make deploying a finished build to WP.org easier. The build folder should be the finished artifact.
