### ISSUE TITLE
Could not deploy

### ISSUE THREAD

**Issue by pdewouters** [stephenharris/grunt-wp-deploy#7]
Any idea what could cause this issue?

```
Warning: Failed to commit to trunk: Error: Command failed: svn: E215004: Authentication failed and interactive prompting is disabled; see the --force-interactive option
svn: E215004: Commit failed (details follow):
svn: E215004: No more credentials or we tried too many times.
Authentication failed
 Use --force to continue.
```

**Comment by nekojira** [comment]
hi @pdewouters  I have incurred in the very same problem!
could you help me out configuring the `~/.subversion/servers` config file please?
I'm not very clear on what should I add there for it to work with wordpress.org repo (I only use svn for this really)
many thanks!
